language: cpp
compiler: gcc
dist: trusty
before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.9; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi
  - sudo pip install cpp-coveralls pyyaml
  - sudo apt-get install -y valgrind libeigen3-dev

script:
- echo "building"
- ./build.sh
- echo "Run tests"
- cd build && make test
- echo "Running valgrind tests on dense matrices..."
- valgrind --leak-check=full --error-exitcode=1 ./build/bin/test_dense
- echo "Running valgrind tests on sparse row major matrices..."
- valgrind --leak-check=full --error-exitcode=1 ./build/bin/test_sparse
- echo "Running valgrind tests on sparse column major matrices..."
- valgrind --leak-check=full --error-exitcode=1 ./build/bin/test_sparse_colmajor
