language: cpp
compiler: gcc
dist: bionic
before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - sudo apt-get install -qq g++
  - sudo pip install cpp-coveralls pyyaml
  - sudo apt-get install -y valgrind libeigen3-dev

script:
- echo "building"
- ./build.sh
- echo "Run tests"
- cd build && make test
- echo "Running valgrind tests on dense matrices..."
- valgrind --leak-check=full --error-exitcode=1 ./bin/test_dense
- echo "Running valgrind tests on sparse row major matrices..."
- valgrind --leak-check=full --error-exitcode=1 ./bin/test_sparse
- echo "Running valgrind tests on sparse column major matrices..."
- valgrind --leak-check=full --error-exitcode=1 ./bin/test_sparse_colmajor
